name: "publish-electron"
on:
  push:
    tags:
      - "v*" # 推送事件匹配 v*, 例如 v1.0，v20.15.10 等来触发工作流

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    name: build and release electron app
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest]
    steps:
      - name: Check out git repository
        uses: actions/checkout@v3.0.0

      - name: Install Node.js
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 18

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
            ~/.cache/electron
            ~/.cache/electron-builder
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dependencies
        run: yarn install --frozen-lockfile --network-timeout=60000

      - name: Build preparation
        run: yarn build

      - name: Setup electron-builder
        working-directory: ./apps/web
        run: |
          yarn remove electron-builder
          yarn add electron-builder@23.6.0 -D

      - name: Build electron windows
        if: matrix.os == 'windows-latest'
        shell: cmd
        run: |
          echo "Current directory:"
          cd apps/web
          echo "Starting Windows build..."
          set DEBUG=electron-builder
          call yarn build-ele:win --debug || (
            echo "Build failed with error code %ERRORLEVEL%"
            type electron-builder.log
            exit /b 1
          )
          echo "Build completed, checking output:"
          dir dist-ele
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEBUG: electron-builder
          NODE_ENV: production

      - name: Build MacOS App
        if: matrix.os == 'macos-latest'
        run: yarn build-ele:mac
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cleanup Windows Artifacts
        if: success() && matrix.os == 'windows-latest'
        shell: cmd
        run: |
          mkdir artifacts
          move apps\web\dist-ele\*.exe artifacts\ 2>nul || echo No exe files found

      - name: Cleanup MacOS Artifacts
        if: success() && matrix.os == 'macos-latest'
        shell: bash
        run: |
          mkdir -p artifacts
          mv apps/web/dist-ele/*.dmg artifacts/ 2>/dev/null || echo "No dmg files found"

      - name: upload artifacts
        uses: actions/upload-artifact@v3.0.0
        with:
          name: ${{ matrix.os }}
          path: artifacts

      - name: release
        uses: softprops/action-gh-release@v0.1.14
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "artifacts/**"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Windows builds
        if: matrix.os == 'windows-latest'
        uses: actions/cache@v3
        with:
          path: |
            %APPDATA%\npm-cache
            %LOCALAPPDATA%\electron
            %LOCALAPPDATA%\electron-builder
          key: ${{ runner.os }}-electron-cache-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-electron-cache-
